### ISSUE TITLE
Update python build to work with rust compiler from stable release channel

### ISSUE THREAD

**Issue by mistergreg** [OvalMoney/celery-exporter#16]
I'm getting build failures when running `pip install celery-exporter` on a system with `rustc 1.39.0` compiler installed on it:
```
    error[E0554]: #![feature] may not be used on the stable release channel
     --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.7.0/src/lib.rs:1:1
      |
    1 | #![feature(specialization)]
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    error: aborting due to previous error
    
    For more information about this error, try `rustc --explain E0554`.
    The following warnings were emitted during compilation:
    
    warning: pyo3 was unable to check rustc compatibility.
    warning: Build may fail due to incompatible rustc version.
    
    error: Could not compile `pyo3`.
```

I'd like to use this library but don't think I can if it is not based on a rust environment from the stable release channel.

Is there a reason why this package relies on a rust environment based on `nightly-2019-06-20`?

**Comment by MRoci** [comment]
it'a pyo3 issue that is tracked [here](https://github.com/PyO3/pyo3/issues/5)

**Comment by nayaks** [comment]
This still doesn't work. Can't build with nightly rust also. PyO3 error is constant.
