### ISSUE TITLE
Pip installation failed with crates.io error

### ISSUE THREAD

**Issue by umaparvat** [OvalMoney/celery-exporter#19]
Hi,
I'm using python 3.6 .when I try to install celery-exporter, it gave error in build rust 
"Rust compiler not found".
I installed setuptools-rust. Rerun pip command for celery exporter Again I got error cargo not found.
Installed rust and cargo rpm using yum in CentOS. In build rust ,now it's trying to read subprocess.command(["cargo","manifest-metadata","cargo.toml"]) exit with error code 1 . It tries to reach crates.io/index  github.com url.
My server is not having internet access. How shall I proceed?.

There is a internal artifactory for python packages but no repository for crates.io

**Comment by SharpEdgeMarshall** [comment]
maybe build the wheel in a machine with internet access?
