### ISSUE TITLE
Can't reference to SSL broker

### ISSUE THREAD

**Issue by behltazor** [OvalMoney/celery-exporter#23]
https://github.com/OvalMoney/celery-exporter/blob/497c8d8bb39d4a808805d1f3340fd84eaff6d0b1/celery_exporter/core.py#L29

can't set `broker_use_ssl` if necessary

Ex. if i use RabbitMQ with TLS i should pass the `broker_url` and tell Celery to use TLS/SSL with the mentioned arg.
`
celery-exporter -b  "pyamqp://<user>:<pwd>@<host>:<port>/<vhost>" --enable-events
`

**Comment by SharpEdgeMarshall** [comment]
Fixing with #55
