### ISSUE TITLE
Cannot install via pipenv

### ISSUE THREAD

**Issue by lukasz-madon** [OvalMoney/celery-exporter#28]
```
pipenv install celery-exporter

Installing celery-exporter…
Error:  An error occurred while installing celery-exporter!
Error text: Collecting celery-exporter (from -r /var/folders/_0/cgwb3f7s5qz6psclx6yvw3ch0000gn/T/pipenv-9nb7gdjr-requirements/pipenv-9tx6mjbb-requirement.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a2/25/497d1aad19bde44ef918cf71be1dc23799126888d40af58e7b5a0e65542e/celery-exporter-1.4.0.tar.gz

    ERROR: Command errored out with exit status 1:
     command: /Users/lukaszmadon/.local/share/virtualenvs/airmed-KQn5-ojZ/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_0/cgwb3f7s5qz6psclx6yvw3ch0000gn/T/pip-install-gvuh58kr/celery-exporter/setup.py'"'"'; __file__='"'"'/private/var/folders/_0/cgwb3f7s5qz6psclx6yvw3ch0000gn/T/pip-install-gvuh58kr/celery-exporter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/_0/cgwb3f7s5qz6psclx6yvw3ch0000gn/T/pip-install-gvuh58kr/celery-exporter/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_0/cgwb3f7s5qz6psclx6yvw3ch0000gn/T/pip-install-gvuh58kr/celery-exporter/setup.py", line 4, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in celery-exporter. Report this to its maintainers.
✘ Installation Failed

```

I think the dependency on rust is missing

**Comment by UtsavPreet** [comment]
So, I installed setuptools-rust & had rustup setup on my machine
yet pip install failed with the following error: 

`      Running `/private/var/folders/1b/15tq7vmj3wx35w20l_psn5bm0000gn/T/pip-install-u4ify3xo/celery-exporter/target/release/build/pyo3-1fa55c831369e837/build-script-build`
    error: failed to run custom build command for `pyo3 v0.7.0`
    
    Caused by:
      process didn't exit successfully: `/private/var/folders/1b/15tq7vmj3wx35w20l_psn5bm0000gn/T/pip-install-u4ify3xo/celery-exporter/target/release/build/pyo3-1fa55c831369e837/build-script-build` (exit code: 101)
    --- stderr
    Error: pyo3 requires a nightly or dev version of Rust.
    Installed version is: 1.45.2 (2020-07-31). Minimum required: 1.34.0-nightly (2019-02-06).
    thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /Users/utsav/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.7.0/build.rs:633:17
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    
    warning: build failed, waiting for other jobs to finish...
    error: build failed
    error: cargo failed with code: 101
    
    ----------------------------------------

**Comment by messense** [comment]
@UtsavPreet Try #27 which uses [https://github.com/PyO3/maturin] to build wheel

**Comment by SharpEdgeMarshall** [comment]
We did a release with compiled wheels so you should be able now to install it, feel free to reopen if it doesn't work.
