### ISSUE TITLE
No response after running it with Docker

### ISSUE THREAD

**Issue by pulkitsapra** [OvalMoney/celery-exporter#32]
Hi! 

I am using this exporter to get the queue length from celery and autoscale in K8 using Prometheus based pipeline.

After running this command. 
`docker run -it --rm ovalmoney/celery-exporter`
There is no output. Kindly see below image.

![image](https://user-images.githubusercontent.com/16730739/95166425-d73f7780-07e8-11eb-8eca-6f4154549dd8.png)

I have no clue what is happening. Can anyone help me regarding this or tell me how to use this exporter with docker-compose ?

**Comment by SharpEdgeMarshall** [comment]
https://prometheus.io/docs/prometheus/latest/getting_started/#starting-up-some-sample-targets

**Comment by arielvinas** [comment]
This is because you didn't set the broker url as explained in the documentation...
