### ISSUE TITLE
How to see exposed metrics.

### ISSUE THREAD

**Issue by pulkitsapra** [OvalMoney/celery-exporter#33]
After attaching to the celery-exporter container via `docker exec`  command, I put the Rabbit MQ url and run the following

`celery-exporter -b "amqp://guest@rabbitmq:5672"`

![image](https://user-images.githubusercontent.com/16730739/95169146-62bb0780-07ed-11eb-9d71-ea0bf019e7ef.png)

In the Readme, it's written 

> If you then look at the exposed metrics, you should see something like this:
`

> celery_tasks_total{name="my_app.tasks.calculate_something",namespace="celery",queue="celery",state="RECEIVED"} 0.0
> celery_tasks_total{name="my_app.tasks.calculate_something",namespace="celery",queue="celery",state="PENDING"} 0.0
> celery_tasks_total{name="my_app.tasks.calculate_something",namespace="celery",queue="celery",state="STARTED"} 0.0
> celery_tasks_total{name="my_app.tasks.calculate_something",namespace="celery",queue="celery",state="RETRY"} 0.0
> celery_tasks_total{name="my_app.tasks.calculate_something",namespace="celery",queue="celery",state="FAILURE"} 0.0
> celery_tasks_total{name="my_app.tasks.calculate_something",namespace="celery",queue="celery",state="REVOKED"} 0.0
> celery_tasks_total{name="my_app.tasks.calculate_something",namespace="celery",queue="celery",state="SUCCESS"} 1.0
> celery_tasks_total{name="my_app.tasks.fetch_some_data",namespace="celery",queue="celery",state="RECEIVED"} 3.0
> celery_tasks_total{name="my_app.tasks.fetch_some_data",namespace="celery",queue="celery",state="PENDING"} 0.0
> celery_tasks_total{name="my_app.tasks.fetch_some_data",namespace="celery",queue="celery",state="STARTED"} 1.0
> celery_tasks_total{name="my_app.tasks.fetch_some_data",namespace="celery",queue="celery",state="RETRY"} 2.0
> celery_tasks_total{name="my_app.tasks.fetch_some_data",namespace="celery",queue="celery",state="FAILURE"} 1.0
> celery_tasks_total{name="my_app.tasks.fetch_some_data",namespace="celery",queue="celery",state="REVOKED"} 0.0
> celery_tasks_total{name="my_app.tasks.fetch_some_data",namespace="celery",queue="celery",state="SUCCESS"} 7.0
...
...
`

How to get this ? Do we have to configure anything in celery worker container ?

**Comment by SharpEdgeMarshall** [comment]
https://prometheus.io/docs/prometheus/latest/getting_started/#starting-up-some-sample-targets
