### ISSUE TITLE
Missing or Invalid Metrics?

### ISSUE THREAD

**Issue by nickatnight** [OvalMoney/celery-exporter#41]
I was searching for a celery exporter and came across this lib. A user on the SO post that lead me here claims there are missing and/or invalid metrics. Has anyone else experienced this? Attaching screenshot

<img width="762" alt="Screen Shot 2021-03-31 at 11 08 52 PM" src="https://user-images.githubusercontent.com/8783431/113251002-66988580-9276-11eb-8031-8af455c86372.png">

Link to post:
https://stackoverflow.com/a/59933594

**Comment by SharpEdgeMarshall** [comment]
Without other information I can't troubleshoot this.
Feel free to reopen if you get more proofs
