### ISSUE TITLE
Remove `maturin sdists` in travis publish

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [OvalMoney/celery-exporter#54]
Following maturin guide [here](https://github.com/PyO3/maturin#pyprojecttoml) during build phase it should build sdist if not explicitly disabled.

ATM with the latest release 1.5.0 I can see source distribution on PyPi https://pypi.org/project/celery-exporter/#files even if `maturin sdist` command was broken.

@xrmx @MRoci I think we could remove it or I'm missing something?

**Comment by xrmx** [comment]
Makes sense, not sure the latest documentation match the version of maturin we are using though.
