### ISSUE TITLE
Build binary wheels

### ISSUE THREAD

**Issue by lpsinger** [OvalMoney/celery-exporter#8]
I'd love to be able to install this without having a rust compiler. Have you thought of building binary manylinux wheels and pushing them to PyPI?

**Comment by SharpEdgeMarshall** [comment]
@MRoci this seems for you 😃

**Comment by lpsinger** [comment]
Thank you! Will you be doing a release soon so that we can install the wheels from PyPI?

**Comment by HaddadJoe** [comment]
Thanks for maintaining this project!
I noticed that latest release v1.4.0 still requires rust compiler. Do you have a release planned anytime soon?

**Comment by sirkonst** [comment]
Is binary wheels avaliable?
